variables:
  MAVEN_OPTS: >-
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository

image: maven:3.9.2-eclipse-temurin-8

cache:
  paths:
    - .m2/repository

# For merge requests do not `deploy` but only run `verify`.
# See https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html
.verify:
  stage: test
  script:
    - 'mvn verify'
  except:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

verify:
  extends:
    - .verify

deploy-to-gitlab:
  stage: deploy
  script:
    - 'mvn deploy -P gitlab-ci'
  only:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

deploy-to-maven-central:
  stage: deploy
  script:
    - 'cat $MAVEN_SETTINGS_SECURITY | base64 -d > $CI_PROJECT_DIR/.m2/settings-security.xml'
    - 'cat $MAVEN_GPG_PRIVATE_KEY | base64 -d > /tmp/maven-central.key'
    - 'gpg --pinentry-mode loopback --passphrase $(echo $MAVEN_GPG_PRIVATE_KEY_PASSPHRASE | base64 -d) --import /tmp/maven-central.key'
    - 'mvn deploy -P maven-central'
  rules:
    - when: manual
